[project]
name = "csv-importer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aqt[qt6]>=25.9.2",
    "mypy>=1.19.1",
]
